# Generated by Django 3.2.7 on 2021-10-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type_of_account',
        ),
        migrations.AddField(
            model_name='user',
            name='buisness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='individual',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
